name: Felipe's Homepage
description: Page with core information about myself and general home for side-projects I might want to do
author: Felipe Xavier Buson
baseurl: /
url: https://fxbuson.github.io/
